### ISSUE TITLE
expose setActiveMonths for configuring separate month instances

### ISSUE THREAD

**Issue by alidcastano** [tresko/react-datepicker#10]
this is a feature request, I'd be great to be able to configure two separate monthly instances 

say you have to month calendar views (one in August and one in September), right now the behavior is that changing the active month changes both of them (so for example if you go back a month the new view is July and August). But it'd be useful to allow changing them separately as well for selecting longer date ranges (so you can have an active view of July and September).

**Comment by alidcastano** [comment]
(i'm using the hooks package, btw)

**Comment by tresko** [comment]
You can use them separately if you will use another useDatepicker hook.

**Comment by alidcastano** [comment]
I considered that but I imagine that they won't be synced together when selecting a date range 

in either case, my use case changed and I don't need this behavior anymore. I still feel that I'd be useful to have but feel free to close this if you're not interested in the feature

**Comment by astabinski** [comment]
@tresko any thoughts about this issue? This functionality looks pretty crucial for selecting date range in two moths selected separately...
