### ISSUE TITLE
Keep calendar visible all the time

### ISSUE THREAD

**Issue by sofiageo** [tresko/react-datepicker#16]
Hello, thanks for the library, it looks pretty nice. 

I have a requirement where the calendar is part of a wizard, so I want to keep it open at all times, and make it use all of it's flexbox container, rather than being a popup. Is this currently possible with a property? Or maybe it's hard to implement, due to how the change of focus works?

Sorry that I had to open a ticket to ask a question, but I couldn't find any other forms of communication on the repository :)

**Comment by sofiageo** [comment]
It works fine with ThemeProvider. Thanks for the example. I'm having an issue when passing a function to the reducer. The function is setFieldValue of the library Formik. When I do that, the calendar closes when I select the endDate. I will keep investigating what causes it to close.

I'm not sure I can help you much with implementing the additional property. I've only been using TS for a few days. But if you are not in a hurry I can give it a try next week.

**Comment by tresko** [comment]
I'm not in a hurry, so you can try.
