### ISSUE TITLE
[feature request] sync date typed into input with calendar

### ISSUE THREAD

**Issue by gentleShark** [tresko/react-datepicker#2]
Awesome library. It would be cool if users could type in the input and have that sync with the calendar. In my use case, users are selecting a license expiration date that is likely years in the future so clicking through the months would add up to a lot of clicks.

**Comment by tresko** [comment]
Thank you. I'll try to do it within two weeks because this week I have no more free time.

**Comment by tresko** [comment]
I did it. You can download v1.6.0.
