### ISSUE TITLE
Change language of react-datepicker

### ISSUE THREAD

**Issue by meesrutten** [tresko/react-datepicker#29]
Hello, I've used the Codesandbox example successfully to reproduce the calendar. 
I was wondering if it is possible to change the language of the calendar i.e. the monthLabel in particular. Is there an example of this available?

**Comment by tresko** [comment]
Yes, you can ;). Check localization story (https://github.com/tresko/react-datepicker/blob/master/packages/styled/src/components/DateRangeInput/DateRangeInput.stories.tsx).
