### ISSUE TITLE
Request for goToNextYear, goToPreviousYear

### ISSUE THREAD

**Issue by moogriento** [tresko/react-datepicker#3]
Hello, is it possible to add the following two methods?

- goToNextYear
- goToPreviousYear

in the useDatepicker hook? It would work just like goToNextMonths / goToPreviousMonths but moving between years.

Thanks

**Comment by tresko** [comment]
Of course, I will add it within 3 days.

**Comment by tresko** [comment]
I included those methods in 1.7.0 release.

**Comment by moogriento** [comment]
Hello, awesome work and thanks for the changes :). It works perfect with `numberOfMonths: 2`

https://codesandbox.io/s/react-example-wqhbd

However if `numberOfMonths` is set to `1`, it takes a weird behaviour

- From `August 2019` -> goToPrevYear turns into `September 2019` (instead of `August 2018`).
- From `August 2019` -> goToNextYear turns into `July 2020` (instead of `August 2020`)

This is a working example explaining that case:
https://codesandbox.io/s/react-example-bqsc5

Is there anything there that can be done? Thanks

**Comment by tresko** [comment]
Thank you. Sorry for this bug. I fixed it in version 1.7.1.

You can check it here: https://codesandbox.io/s/react-example-qz8p1

If you want to contribute or have some ideas you can write to me at twitter (https://twitter.com/tresko9) or email me (sedej.miha@gmail.com).

Kind regards,

Miha

**Comment by moogriento** [comment]
Works perfect. Thanks!
