### ISSUE TITLE
How to pass z-index property to dateRangeDatepickerWrapper

### ISSUE THREAD

**Issue by ProjectINT** [tresko/react-datepicker#32]
I'm using this date range picker in the modal popup, and I need to pass z-index to calendar wrapper, is it's possible?

**Comment by tresko** [comment]
It isn't supported. Where do you need z-index?

**Comment by ProjectINT** [comment]
> It isn't supported. Where do you need z-index?
I am using this daterangepicker as part of the popup form. When I'm open it, the calendar is situated under neighbor inputs, for now, I decide it with the hack, I change z-index on neighbor inputs when focusedInput !== null. 
It would be nice to add z-index prop to theme provider.

**Comment by goxr3plus** [comment]
I had exactly the same problem and i added it on the bootstrap `<Col>` which contains the `DatePicker`.

@ProjectINT

**Comment by MarianyFerreira** [comment]
I have the same problem

**Comment by goxr3plus** [comment]
@MarianyFerreira  You can do :

          <Col md={6} style={{ zIndex: '50' }}>
            .....
          </Col>
          <Col md={6} style={{ zIndex: '100' }}>
            {datePicker}
          </Col>

and play around with the layout.

**Comment by goxr3plus** [comment]
@tresko  Please help us on a better solution :)

**Comment by tresko** [comment]
I will do it today or tomorrow. Do you need z-index anywhere else?

**Comment by tresko** [comment]
Added 3 new styles in v2.2: datepickerZIndex, dateRangeZIndex, dateSingleZIndex
