### ISSUE TITLE
How to change date format :) ?

### ISSUE THREAD

**Issue by goxr3plus** [tresko/react-datepicker#37]
The default date format is `MM/DD/YYYY` i want to change it to `DD/MM/YYYY` how this can be done :) ?

**Comment by goxr3plus** [comment]
![image](https://user-images.githubusercontent.com/20374208/69819809-539c1e00-1208-11ea-9764-79b669f9f467.png)

**Comment by tresko** [comment]
Use `displayFormat` prop.
