### ISSUE TITLE
ie11 doesn't have ms prefixes (and missing IE11 full support)

### ISSUE THREAD

**Issue by reduxdj** [tresko/react-datepicker#41]
According to this article, repeat is not provided by IE11, and when rendering the grid, the alignment is off.

https://stackoverflow.com/questions/45786788/css-grid-layout-not-working-in-ie11-even-with-prefixes

The following is observed in IE11:
1. the component doesn't show elements side by side
2. the first day of the month is always sunday
3. input elements are stacked

**@datepicker-react/hooks or @datepicker-react/styled version**
e.g. @datepicker-react/hooks@2.2.0

**Describe the bug**

**Source code (including props configuration)**
```
<DateRangeInput
  onDatesChange={data => dispatch({type: 'dateChange', payload: data})}
  onFocusChange={focusedInput => dispatch({type: 'focusChange', payload: focusedInput})}
  startDate={state.startDate} // Date or null
  endDate={state.endDate} // Date or null
  focusedInput={state.focusedInput} // START_DATE, END_DATE or null
/>
```
If you have custom methods that you are passing into a `@datepicker-react` component / hooks, please include the source for those as well.

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Is the issue reproducible in Storybook?**
Please link to the relevant storybook example

**Additional context**

**Comment by tresko** [comment]
IE11 is not supported.
