### ISSUE TITLE
Block multiple dates

### ISSUE THREAD

**Issue by mikeybell** [tresko/react-datepicker#44]
**@datepicker-react/hooks@2.20**

Wondering if there is a way to pass multiple dates to `isDateBlocked`? I see in your `styled` example you have blocked a single date.

I have an array of dates I need to block off, wondering if you have a solution for this? I could not find anything while digging around in the code.

```
const { isDateBlocked } = useDatepicker({ isDateBlocked: arrayOfDatesToGoHere });
```
Thanks for you work on this project!

**Comment by tresko** [comment]
You can block multiple dates. isDateBlocked is executed for every single day and if you return true, then the date is disabled, otherwise, it is enabled.

```
isDateBlocked: (date) => {
  if (date .....) {
    return true
  }
  return false
}
```

**Comment by tresko** [comment]
In v2.3.0 you can pass `unavailableDates` prop.

```
<Datepicker
  unavailableDates={[new Date(), new Date(), new Date()...]]}
   ...
/>
```
