### ISSUE TITLE
Centering datepicker?

### ISSUE THREAD

**Issue by Djo1e** [tresko/react-datepicker#59]
**Current State**
![before](https://user-images.githubusercontent.com/34274884/73739993-9c5fde00-4747-11ea-8fdc-96e4c5ba5f10.png)

**Desired State**
![after](https://user-images.githubusercontent.com/34274884/73740028-a71a7300-4747-11ea-88cb-de657b0c0988.png)

What would an appropriate way to achieve this? I tried looking into [Theme Props](https://github.com/tresko/react-datepicker/blob/master/docs/THEME_PROPS.md) but couldn't find the props I need to make the adjustment.

**Comment by tresko** [comment]
You can try with You can `datepickerCloseWrapperLeft` override style .

https://github.com/tresko/react-datepicker/blob/master/docs/THEME_PROPS.md
