### ISSUE TITLE
Issues with responsive display

### ISSUE THREAD

**Issue by nomadsworld** [tresko/react-datepicker#63]
@datepicker-react/styled version 2.3.1

More of a question rather than a bug.

How do you get the datepicker to behave responsively. At the moment when vertical is set to false, the two calendars display horizontally and expand beyond the screen on mobile. Is there a setting to make this responsive?

**Source code (including props configuration)**
<DateRangeInput
          onDatesChange={data => {
            dispatch({ type: "dateChange", payload: data });
            register({ name: "Start Date", type: "custom" });
            register({ name: "End Date", type: "custom" });
            setValue("Start Date", data.startDate);
            setValue("End Date", data.endDate);
          }}
          onFocusChange={focusedInput =>
            dispatch({ type: "focusChange", payload: focusedInput })
          }
          startDate={state.startDate} // Date or null
          endDate={state.endDate} // Date or null
          focusedInput={state.focusedInput} // START_DATE, END_DATE or null
        />
```
If you have custom methods that you are passing into a `@datepicker-react` component / hooks, please include the source for those as well.

Note datepicker being used with react-hook-form. Should not effect display

**Screenshots/Gifs**


https://recordit.co/u6Xu9ahRUJ

**Smartphone (please complete the following information):**

Testing in browser, and on iphone 7 all browsers

**Is the issue reproducible in Storybook?**
Yes https://react-datepicker.netlify.com/?path=/story/daterangeinput--simple-demo

**Additional context**

Nope.

I love your work. This has been the best experience I have had with a react datepicker component. Thanks!

**Comment by tresko** [comment]
You can override styles.

https://github.com/tresko/react-datepicker/blob/master/docs/THEME_PROPS.md

```datepickerCloseWrapperRight?: ResponsiveValue<RightProperty<TLengthStyledSystem>>
datepickerCloseWrapperTop?: ResponsiveValue<TopProperty<TLengthStyledSystem>>
datepickerCloseWrapperLeft?: ResponsiveValue<LeftProperty<TLengthStyledSystem>>
datepickerCloseWrapperBottom?: ResponsiveValue<BottomProperty<TLengthStyledSystem>>````
