### ISSUE TITLE
How to localize?

### ISSUE THREAD

**Issue by PhilGarb** [tresko/react-datepicker#67]
First of all you have build an amazing datepicker. It works fast, very well and looks excellent. I have however not been able to understand how to localize the months and days. 

By checking the storybook implementation I have seen, that you are using a function to get the labels. Is this function provided by the library or do I have to provide the labels in another way? In which format would I have to provide the labels?

I understand that it might be something coming from the hooks library and probably the functions  dayLabelFormat, weekdayLabelFormat and monthLabelFormat. If that assumption is correct could you specify how to use these functions?

If I fully understand the process I could also write a little more documentation and submit a pull request, because this might be the hardest implementation aspect of this excellent component.

**Comment by tresko** [comment]
Thank you.

You pass the phrases as an object. DayLabelFormat, weekdayLabelFormat, and monthLabelForm, these are functions (callbacks) that take a date as an argument and return a string - formatted label. Below is an example with date-fns, but you can also use a moment or you can format labels by yourself.

Here is an example:`
```js
import {es as locale} from 'date-fns/locale'
import {format} from 'date-fns'

function Test() {
  return (
    <DateRangeInput
      ...otherProps,
      displayFormat={displayFormat}
      phrases={{
        datepickerStartDatePlaceholder: 'Seleccionar',
        datepickerStartDateLabel: 'Fecha de inicio:',
        datepickerEndDatePlaceholder: 'Seleccionar',
        datepickerEndDateLabel: 'Fecha de inicio:',
        resetDates: 'Deshacer',
        startDateAriaLabel: 'Fecha de inicio',
        endDateAriaLabel: 'Fecha de inicio',
        startDatePlaceholder: 'Fecha de inicio',
        endDatePlaceholder: 'Fecha de inicio',
        close: 'Cerca',
      }}
      displayFormat={text('displayFormat', 'MM/dd/yyyy')}
      dayLabelFormat={(date: Date) => format(date, 'dd', {locale})}
      weekdayLabelFormat={(date: Date) => format(date, 'eeeeee', {locale})}
      monthLabelFormat={(date: Date) => format(date, 'MMMM yyyy', {locale})}
    />
  )
}
```

Here is a list of all possible phrases [click](https://github.com/tresko/react-datepicker/blob/master/packages/styled/src/phrases.ts)

**Comment by PhilGarb** [comment]
Thank you so much :) This worked for me. I guess my problem was more with how date-fns handles localization and less about this library after all. 

Are you interested in a pull request which takes your answer and maybe a link and small explanation of a date-fns example to extend the Readme?

**Comment by tresko** [comment]
Yes, of course.
