### ISSUE TITLE
Wrong dates for september 2019

### ISSUE THREAD

**Issue by jonespen** [tresko/react-datepicker#7]
**@datepicker-react/hooks**

**Describe the bug**

1th September 2019 should be on a Sunday (when week starts on monday), but is Tuesday. I added some failing tests here: https://github.com/jonespen/react-datepicker/commit/cf776b79f84a2f529abf591f9f8817386306d9ea. Guess it's something in `getDays`, but couldn't figure out the logic

**Source code (including props configuration)**
See codesandbox https://codesandbox.io/s/clever-meadow-1ur39

**Screenshots/Gifs**
![image](https://user-images.githubusercontent.com/230841/63940441-c19a4300-ca69-11e9-9292-692af1df6815.png)

For reference, see Calendar.app screenshot:
![image](https://user-images.githubusercontent.com/230841/63940656-3c635e00-ca6a-11e9-8603-b2a630361c5e.png)

**Comment by tresko** [comment]
Fixed in version 2.0.2.

Codesandbox: https://codesandbox.io/s/blissful-bardeen-118ym

**Comment by jonespen** [comment]
Great, thanks!
