### ISSUE TITLE
zIndex problem with react Material-ui

### ISSUE THREAD

**Issue by intobrackets** [tresko/react-datepicker#71]
**@datepicker-react/hooks or @datepicker-react/styled version**
e.g. @datepicker-react/hooks@2.3.1

**Describe the bug**
zIndex problem with react Material-ui

![image](https://user-images.githubusercontent.com/3481301/77463383-d5dace80-6e05-11ea-9c19-565350e737c9.png)

**Source code (including props configuration)**
```
<>
      <ThemeProvider
        theme={{
          breakpoints: ["32em", "48em", "64em"],
          reactDatepicker: {
            dateRangeZIndex: 9999999,
            daySize: [36, 40],
            fontFamily: "system-ui, -apple-system",
            colors: {
              accessibility: "#D80249",
              selectedDay: "#f7518b",
              selectedDayHover: "#F75D95",
              primaryColor: "#d8366f"
            }
          }
        }}
      >
        <DateRangeInput
          onDatesChange={data =>
            dispatch({ type: "dateChange", payload: data })
          }
          onFocusChange={focusedInput =>
            dispatch({ type: "focusChange", payload: focusedInput })
          }
          startDate={state.startDate} // Date or null
          endDate={state.endDate} // Date or null
          focusedInput={state.focusedInput} // START_DATE, END_DATE or null
        />
      </ThemeProvider>
      <Button type="submit" color="primary" variant="contained">
        Submit
      </Button>
    </>
```
If you have custom methods that you are passing into a `@datepicker-react` component / hooks, please include the source for those as well.

**Screenshots/Gifs**
If applicable, add screenshots or gifs to help explain your problem.

Code Example to reproduce problem:
https://codesandbox.io/s/theming-datepicker-reactstyled-3vi2i

**Comment by tresko** [comment]
If you update @datepicker-react/styled to the latest version, it will work.

**Comment by intobrackets** [comment]
> If you update @datepicker-react/styled to the latest version, it will work.

i am using the last verion : 2.3.1

**Comment by tresko** [comment]
In this example is version 1.5.0.

**Comment by tresko** [comment]
It works here with the latest version:
https://codesandbox.io/s/theming-datepicker-reactstyled-6pwrd
