### ISSUE TITLE
Bundlesize regression for hooks 

### ISSUE THREAD

**Issue by zmitry** [tresko/react-datepicker#8]
![image](https://user-images.githubusercontent.com/14317641/64202986-32db5b00-ce9b-11e9-8372-24bb722e8914.png)
filesize changed from 5kb to 11kb, it's probably issue somewhere. 
https://bundlephobia.com/result?p=@datepicker-react/hooks@2.0.2

**Comment by tresko** [comment]
We upgraded date-fns and in version v2.0.0, therefore, the bundle size increased (https://bundlephobia.com/result?p=date-fns@2.0.1).

I need to examine what changed in date-fns and if tree shaking works properly.
