### ISSUE TITLE
How to set default start and end date

### ISSUE THREAD

**Issue by sommesh** [tresko/react-datepicker#81]
<DateRangeInput
      onDatesChange={data => dispatch({type: 'dateChange', payload: data})}
      onFocusChange={focusedInput => dispatch({type: 'focusChange', payload: focusedInput})}
      startDate={state.startDate} // Date or null
      endDate={state.endDate} // Date or null
      focusedInput={state.focusedInput} // START_DATE, END_DATE or null
    />

In DateRangeInput is there any way to set default startDate and endDate when the UI is rendered first?

And how shall we disable the edit option?

https://prnt.sc/s6v96u

**Comment by tresko** [comment]
Here is an example:

```
const initialState = {
  startDate: new Date(), // Default start date
  endDate: new Date(), // Default end date
  focusedInput: null
};

function reducer(state, action) {
  switch (action.type) {
    case "focusChange":
      return { ...state, focusedInput: action.payload };
    case "dateChange":
      return action.payload;
    default:
      throw new Error();
  }
}
```
