### ISSUE TITLE
Help to set custom style

### ISSUE THREAD

**Issue by c3s4** [tresko/react-datepicker#85]
Hi,
is there a way to style the input field just to have only the bottom border?
I don't know styled-system, I'm trying to understand if is possible, but looking to your code seems the `inputLabelBorder` is for all borders and is not possible to set just one.

Maybe is only my lack of knowledge on `styled-system`.

Thank you

**Comment by ReTWi** [comment]
@c3s4  here is example https://codesandbox.io/s/theming-datepicker-reactstyled-42pdb?fontsize=14

**Comment by subhendukundu** [comment]
On the same context,
When styles have a borderRadius of 10px, like
```
inputLabelBorder: '1px solid rgba(226, 226, 226, 0.5)',
inputLabelBorderRadius: '10px', 
```
Border corners are off due to components inside. Is there a way to put `border-radius: 10px;` on the input?
