### ISSUE TITLE
Input losing focus when I used arrows in datepicker

### ISSUE THREAD

**Issue by martinadamec** [tresko/react-datepicker#91]
**@datepicker-react/hooks@2.4.0**

**Describe the bug**
When I have an input in the same page with a datepicker, I use arrows for navigate in the datepicker, after that ...I hit a key in the input, input lose focus and datepicker has focus back (at last focused day).

I created a repo with this bug. It is happen with CRA (create react app). I used base example plus default html input.

**Source code (including props configuration)**
https://github.com/martinadamec/datepicker-hooks-lose-input-focus-bug

**Screen record**
https://github.com/martinadamec/datepicker-hooks-lose-input-focus-bug/blob/master/screen-record.mov

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome (83), Firefox (77)

---
Any idea what is wrong? Thank you Martin.

**Comment by tresko** [comment]
Hi, I don't know. I will need to examine it.

**Comment by m7kvqbe1** [comment]
We are also experiencing this same issue - has this recently been introduced?

**Comment by m7kvqbe1** [comment]
This appears to be related to the `dayRef` used to initialise the `useDay` hook.

By removing the ref from our rendered JSX element we were able to resolve this issue.

**Comment by martinadamec** [comment]
> This appears to be related to the `dayRef` used to initialise the `useDay` hook.
> 
> By removing the ref from our rendered JSX element we were able to resolve this issue.

nice :), would you do a PR? or at least fork the repo with these changes?

**Comment by m7kvqbe1** [comment]
Will do - I'll update this issue tomorrow morning with more information.

**Comment by m7kvqbe1** [comment]
https://github.com/tresko/react-datepicker/blob/ba5d98884279e206b381bf768e226f812ee8e951/packages/hooks/src/useDay/useDay.ts#L36

I think the issue relates to this line.

**Comment by tresko** [comment]
Thank you. I will do a PR in the afternoon.

**Comment by tresko** [comment]
Should be fixed in version 2.4.1.
